"""Session models - therapy sessions and summaries"""

from sqlalchemy import (
    Column, String, Text, JSON, Boolean, Integer,
    ForeignKey, Date, DateTime, Enum as SQLEnum,
)
from sqlalchemy.orm import relationship
from app.models.base import BaseModel
import enum


class SessionType(str, enum.Enum):
    """Type of therapy session"""
    INDIVIDUAL = "individual"
    COUPLES = "couples"
    FAMILY = "family"
    GROUP = "group"
    INTAKE = "intake"
    FOLLOW_UP = "follow_up"


class SummaryStatus(str, enum.Enum):
    """Summary review status"""
    DRAFT = "draft"
    APPROVED = "approved"


class Session(BaseModel):
    """Therapy session record"""

    __tablename__ = "sessions"

    therapist_id = Column(Integer, ForeignKey("therapists.id"), nullable=False)
    patient_id = Column(Integer, ForeignKey("patients.id"), nullable=False)

    # Session Info
    session_date = Column(Date, nullable=False)
    start_time = Column(DateTime, nullable=True)   # Scheduled start (date+time)
    end_time = Column(DateTime, nullable=True)      # Scheduled end (date+time)
    session_type = Column(SQLEnum(SessionType, native_enum=False), default=SessionType.INDIVIDUAL)
    duration_minutes = Column(Integer)  # Session duration

    # Session Number
    session_number = Column(Integer)  # e.g., session 5 out of total

    # Recording Info
    audio_file_path = Column(String(500))  # Path to encrypted audio file
    has_recording = Column(Boolean, default=False)

    # Summary (generated by AI)
    summary_id = Column(Integer, ForeignKey("session_summaries.id"))

    # Relationships
    therapist = relationship("Therapist", back_populates="sessions")
    patient = relationship("Patient", back_populates="sessions")
    summary = relationship("SessionSummary", back_populates="session", uselist=False)


class SessionSummary(BaseModel):
    """
    AI-generated session summary in therapist's style
    This is auto-generated after each session
    """

    __tablename__ = "session_summaries"

    # Summary Content (in therapist's personal style!)
    topics_discussed = Column(JSON)  # List of topics
    interventions_used = Column(JSON)  # Therapeutic interventions
    patient_progress = Column(Text)  # Progress notes
    homework_assigned = Column(JSON)  # Exercises assigned
    next_session_plan = Column(Text)  # Plan for next session

    # Full Summary Text
    full_summary = Column(Text)  # Complete formatted summary

    # Metadata
    generated_from = Column(String(50))  # "audio", "text", "manual"
    therapist_edited = Column(Boolean, default=False)
    approved_by_therapist = Column(Boolean, default=False)
    status = Column(
        SQLEnum(SummaryStatus, native_enum=False),
        default=SummaryStatus.DRAFT,
        nullable=False,
    )

    # Clinical Observations
    mood_observed = Column(String(100))
    risk_assessment = Column(Text)  # Safety/risk notes

    # Relationship
    session = relationship("Session", back_populates="summary")
