"""Session models - therapy sessions and summaries"""

from sqlalchemy import (
    Column, String, Text, JSON, Boolean, Integer, Float,
    ForeignKey, Date, DateTime, Enum as SQLEnum,
)
from sqlalchemy.orm import relationship
from app.models.base import BaseModel
import enum


class SessionType(str, enum.Enum):
    """Type of therapy session"""
    INDIVIDUAL = "individual"
    COUPLES = "couples"
    FAMILY = "family"
    GROUP = "group"
    INTAKE = "intake"
    FOLLOW_UP = "follow_up"


class SummaryStatus(str, enum.Enum):
    """Summary review status"""
    DRAFT = "draft"
    APPROVED = "approved"


class Session(BaseModel):
    """Therapy session record"""

    __tablename__ = "sessions"

    therapist_id = Column(Integer, ForeignKey("therapists.id"), nullable=False)
    patient_id = Column(Integer, ForeignKey("patients.id"), nullable=False)

    # Session Info
    session_date = Column(Date, nullable=False)
    start_time = Column(DateTime, nullable=True)   # Scheduled start (date+time)
    end_time = Column(DateTime, nullable=True)      # Scheduled end (date+time)
    session_type = Column(SQLEnum(SessionType, native_enum=False), default=SessionType.INDIVIDUAL)
    duration_minutes = Column(Integer)  # Session duration

    # Session Number
    session_number = Column(Integer)  # e.g., session 5 out of total

    # Recording Info
    audio_file_path = Column(String(500))  # Path to encrypted audio file
    has_recording = Column(Boolean, default=False)

    # Summary (generated by AI)
    summary_id = Column(Integer, ForeignKey("session_summaries.id"))

    # Relationships
    therapist = relationship("Therapist", back_populates="sessions")
    patient = relationship("Patient", back_populates="sessions")
    summary = relationship("SessionSummary", back_populates="session", uselist=False)


class SessionSummary(BaseModel):
    """
    AI-generated session summary in therapist's style
    This is auto-generated after each session
    """

    __tablename__ = "session_summaries"

    # Summary Content (in therapist's personal style!)
    topics_discussed = Column(JSON)  # List of topics
    interventions_used = Column(JSON)  # Therapeutic interventions
    patient_progress = Column(Text)  # Progress notes
    homework_assigned = Column(JSON)  # Exercises assigned
    next_session_plan = Column(Text)  # Plan for next session

    # Full Summary Text
    full_summary = Column(Text)  # Complete formatted summary

    # Transcript (stored separately for audit — PRD Feature 2)
    transcript = Column(Text)  # Raw ASR transcript, kept alongside summary

    # Metadata
    generated_from = Column(String(50))  # "audio", "text", "manual"
    therapist_edited = Column(Boolean, default=False)
    approved_by_therapist = Column(Boolean, default=False)
    status = Column(
        SQLEnum(SummaryStatus, native_enum=False),
        default=SummaryStatus.DRAFT,
        nullable=False,
    )

    # Clinical Observations
    mood_observed = Column(String(100))
    risk_assessment = Column(Text)  # Safety/risk notes

    # AI Generation Metadata (added migration 014)
    # Stores the original AI output before any therapist edits.
    # CRITICAL: signature engine learning only uses approved rows; this field
    # lets us compute edit distance (ai_draft_text vs final full_summary).
    ai_draft_text = Column(Text)
    ai_model = Column(String(200))           # model that generated this summary
    ai_prompt_version = Column(String(50))   # prompt version tag at generation time
    ai_confidence = Column(Integer)          # 0–100 confidence from generation call
    modality_pack_id = Column(Integer, ForeignKey("modality_packs.id",
                                                   ondelete="SET NULL"))

    # Completeness check results (added migration 015)
    completeness_score = Column(Float, nullable=True)  # 0.0–1.0; -1.0 = checker error
    completeness_data = Column(JSON, nullable=True)    # full CompletenessResult dict

    # Session Summary 2.0 (added migration 016)
    clinical_json = Column(JSON, nullable=True)        # intermediate extraction artifact (Call 1)
    therapist_edit_distance = Column(Integer, nullable=True)  # chars changed vs ai_draft_text

    # Relationship
    session = relationship("Session", back_populates="summary")
